version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  nest-api:
    build: .
    container_name: nest-api
    depends_on:
      - mysql
    restart: always
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
      DB_NAME: myapp
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data: