@baseUrl = http://localhost:3000/users
@userId = c92a3262-098e-4682-99f5-616dda1076e8
@deleteUserId = 92143cae-67e5-4b17-9490-7683746715cd

### get users
GET {{baseUrl}}

### get user
GET {{baseUrl}}/{{userId}}

### create user
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Sandra Alves",
  "email": "email@email.com",
  "password": "password"
}

### update user
PATCH  {{baseUrl}}/{{userId}}
Content-Type: application/json

{
  "name": "Sandra Evangelista",
  "email": "emaills@email.com",
  "password": "pablo123"
}

### delete user
DELETE  {{baseUrl}}/{{deleteUserId}}

