@baseUrl = http://localhost:3000/users
@userId = 
@deleteUserId = 

@adminRoleId = 

@authToken = 

### get users
GET {{baseUrl}}?page=1&limit=4
Authorization: Bearer {{authToken}}

### get user
GET {{baseUrl}}/{{userId}}
Authorization: Bearer {{authToken}}

### get user
GET {{baseUrl}}/me
Authorization: Bearer {{authToken}}

### create user
POST {{baseUrl}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "name",
  "email": "email@email",
  "password": "password"
}

### update user
PATCH  {{baseUrl}}/{{userId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "name",
  "password": "password"
}

### delete user
DELETE  {{baseUrl}}/{{deleteUserId}}
Authorization: Bearer {{authToken}}

