@baseUrl = http://localhost:3000/users
@userId = c92a3262-098e-4682-99f5-616dda1076e8
@deleteUserId = cc9ffe9b-ccd6-4670-b717-ebccc617b628

@adminRoleId = 5f7f6f19-93e4-4628-a8c4-f5325d85e698

### get users
GET {{baseUrl}}

### get user
GET {{baseUrl}}/{{userId}}

### create user
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Pablo allves",
  "email": "pablo@email.com",
  "password": "123456",
  "roles": ["{{adminRoleId}}"]
}

### update user
PATCH  {{baseUrl}}/{{userId}}
Content-Type: application/json

{
  "name": "Sandra Evangelista",
  "email": "emaills@email.com",
  "password": "pablo123"
}

### delete user
DELETE  {{baseUrl}}/{{deleteUserId}}

