@baseUrl = http://localhost:3000/roles

@roleId = 5f7f6f19-93e4-4628-a8c4-f5325d85e698

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MzU1YzE4My1hMDY2LTQ4MDQtOWE3Yi02NjU0MjE2MTVhNWIiLCJpYXQiOjE3NDc1MjY2OTYsImV4cCI6MTc0NzYxMzA5Nn0.1CTAUCVHWTMGUx3dwvGbQKsUt60vrYXNsCplFyDIiq0

### get roles
GET {{baseUrl}}
Authorization: Bearer {{authToken}}

### get role
GET {{baseUrl}}/{{roleId}}
Authorization: Bearer {{authToken}}

### create role

POST {{baseUrl}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "role": "Convidado(a)"
}

### update user
PATCH  {{baseUrl}}/{{roleId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "role": "Administrador(a)"
}