@baseUrl = http://localhost:3000/roles

@roleId = 

@authToken = 

### get roles
GET {{baseUrl}}
Authorization: Bearer {{authToken}}

### get role
GET {{baseUrl}}/{{roleId}}
Authorization: Bearer {{authToken}}

### create role

POST {{baseUrl}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "role": "Admin"
}

### update role
PATCH  {{baseUrl}}/{{roleId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "role": "Administrador(a)"
}