@baseUrl = http://localhost:3000/auth
@email = pabloconv@email.com
@password = 123456

###  sign in user
POST {{baseUrl}}/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}
